spring:
    datasource:
        url: jdbc:postgresql://localhost/test
        username: liuyi
        password: 123456
    jpa:
        hibernate:
            ddl-auto: create
#    r2dbc:
#        url: 127.0.0.1
#        username: liuyi
#        password: 123456
